"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type LanguageCode = 'de' | 'en' | 'tr' | 'ku' | 'ar';
type Language = LanguageCode | null;

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
    de: {
        "hero.title": "DEIN TERMIN.",
        "hero.subtitle": "PREMIUM TERMINE FÜR DEN MODERNEN GENTLEMAN",
        "book.button": "TERMIN BUCHEN",
        "select.services": "DIENSTLEISTUNGEN",
        "select.time": "ZEIT WÄHLEN",
        "select.barber": "BARBIER WÄHLEN",
        "select.date": "DATUM WÄHLEN",
        "confirmed": "BESTÄTIGT",
        "summary": "Zusammenfassung",
        "total": "Gesamt",
        "next": "Weiter",
        "confirm": "Bestätigen",
        "back": "Zurück",
        "nav.home": "START",
        "nav.info": "INFO",
        "nav.gallery": "GALERIE",
        "nav.book": "BUCHEN",
        "nav.manage": "TEILNAHME VERWALTEN",
        "manage.title": "Termine verwalten",
        "manage.subtitle": "Geben Sie Ihre Telefonnummer ein, um Ihre Termine zu sehen.",
        "manage.placeholder": "Telefonnummer",
        "manage.find": "Suchen",
        "manage.no_appts": "Keine Termine gefunden.",
        "manage.cancel": "Stornieren",

        "manage.cancel_confirm": "Möchten Sie diesen Termin wirklich stornieren?",
        "manage.cancel_too_late": "Termine, die in weniger als 24 Stunden stattfinden, können nicht storniert werden.",
        "contact.details": "KONTAKT",
        "contact.title": "Kontaktdaten",
        "contact.phone": "Telefonnummer",
        "contact.email": "E-Mail",
        "contact.required": "Bitte geben Sie Telefon oder E-Mail an.",
        "contact.disclaimer": "Bitte geben Sie Ihre E-Mail-Adresse oder Telefonnummer an, damit wir Sie kontaktieren können, falls Ihr Termin nicht bestätigt werden kann.",
        "book.another": "Weiteren Termin buchen",
        "contact.name": "Vor- und Nachname",

        "gallery.interior": "Barber Interieur",
        "gallery.tools": "Professionelle Werkzeuge",
        "gallery.lounge": "Wartebereich",

        "select.service_prompt": "Wählen Sie eine Dienstleistung, um zu beginnen.",
        "unit.mins": "Min",

        "contact.placeholder_name": "Max Mustermann",
        "contact.placeholder_phone": "+49 123 4567890",
        "contact.placeholder_email": "beispiel@mail.com",

        "admin.login.title": "Admin Zugang",
        "admin.login.subtitle": "Bitte Passwort eingeben",
        "admin.login.button": "Anmelden",
        "admin.login.error": "Falsches Passwort",
        "admin.nav.dashboard": "Übersicht",
        "admin.nav.termins": "Termine",
        "admin.nav.services": "Dienstleistungen",
        "admin.nav.barbers": "Barbiere",
        "admin.nav.plan": "Plan",
        "admin.nav.availability": "Arbeitstage",
        "admin.logout": "Abmelden",

        "av.day_off": "Freier Tag",
        "av.working": "Arbeitet",
        "av.cancel": "Abbrechen",
        "av.set_off": "Als freien Tag markieren",
        "av.set_working": "Als Arbeitstag markieren",

        "admin.stats.total_revenue": "GESAMTEINNAHMEN",
        "admin.stats.confirmed_appointments": "BESTÄTIGTE TERMINE",
        "admin.stats.pending_approvals": "AUSSTEHENDE GENEHMIGUNGEN",

        "admin.dashboard.pending_title": "Ausstehende Anfragen",
        "admin.dashboard.pending_empty": "Keine ausstehenden Termine.",
        "admin.dashboard.pending_subtitle": "Neue Buchungen erscheinen hier automatisch.",
        "admin.btn.approve": "Bestätigen",
        "admin.btn.reject": "Ablehnen",
        "admin.btn.delete_confirm": "Termin wirklich ablehnen und löschen?",

        "confirmation.cash_warning": "Bitte vergessen Sie nicht, den Betrag in bar mitzubringen.",
        "confirmation.message": "Ihr Termin ist bestätigt für {time} am {date}",
        "confirmation.barber": "Barbier: {name}",

        "info.location": "Standort",
        "info.opening_hours": "Öffnungszeiten",
        "info.get_directions": "Wegbeschreibung",
        "info.closed": "Geschlossen",
        "days.monday": "Montag",
        "days.tuesday": "Dienstag",
        "days.wednesday": "Mittwoch",
        "days.thursday": "Donnerstag",
        "days.friday": "Freitag",
        "days.saturday": "Samstag",
        "days.sunday": "Sonntag",

        "admin.barbers.title": "Teamverwaltung",
        "admin.barbers.subtitle": "Verwalten Sie Ihre Barbiere",
        "admin.barbers.add_btn": "Barbier hinzufügen",
        "admin.barbers.delete_confirm": "Möchten Sie diesen Barbier wirklich entfernen?",
        "admin.barbers.modal_title": "Neuen Barbier hinzufügen",
        "admin.barbers.edit_title": "Barbier bearbeiten",
        "admin.barbers.name_label": "Name",
        "admin.barbers.specialty_label": "Spezialgebiet",
        "admin.barbers.specialty_placeholder": "z.B. Meisterbarbier",
        "admin.barbers.save": "Speichern",
        "admin.barbers.cancel": "Abbrechen",

        "admin.termins.title": "Bestätigte Termine",
        "admin.termins.empty": "Noch keine bestätigten Termine.",
        "admin.termins.empty_sub": "Bestätigte Buchungen erscheinen hier.",
        "admin.termins.date": "Datum & Zeit",
        "admin.termins.customer": "Kunde",
        "admin.termins.barber": "Barbier",
        "admin.termins.contact": "Kontakt",
        "admin.termins.services": "Dienstleistungen",
        "admin.termins.total": "Gesamt",
        "admin.termins.delete_confirm": "Termin endgültig löschen?",

        "admin.calendar.daily_title": "Tagesplan",
        "admin.calendar.select_barber": "Barbier wählen",
        "admin.calendar.select_barber_msg": "Wählen Sie ein Teammitglied, um dessen Arbeitstage zu verwalten.",
        "admin.calendar.manage_for": "Verfügbarkeit verwalten für",
        "admin.months": "Januar,Februar,März,April,Mai,Juni,Juli,August,September,Oktober,November,Dezember",
        "admin.days.short": "Mo,Di,Mi,Do,Fr,Sa,So",
        "admin.services.manage": "Dienstleistungen verwalten",
        "admin.services.auto_save": "Änderungen werden sofort gespeichert.",
        "admin.services.new": "Neu",
        "admin.services.loading": "Lade Daten...",
        "admin.services.add_new": "Neue Dienstleistung",
        "admin.services.confirm_delete": "Sind Sie sicher?",
        "admin.services.error_add": "Fehler beim Hinzufügen",
        "admin.services.add_btn": "Zur Liste hinzufügen",
        "admin.services.empty": "Keine Dienstleistungen vorhanden.",
        "admin.services.name_de": "Name (Deutsch) *",
        "admin.services.name_en": "Name (Englisch)",
        "admin.services.name_tr": "Name (Türkisch)",
        "admin.services.price": "Preis (€) *",
        "admin.services.duration": "Dauer (Min)",
        "admin.calendar.no_appts": "Keine Termine für diesen Tag.",
        "admin.calendar.schedule_for": "Plan für",
        "admin.calendar.view_schedule_msg": "Wählen Sie ein Teammitglied, um dessen Plan zu sehen."
    },
    en: {
        "hero.title": "YOUR APPOINTMENT.",
        "hero.subtitle": "PREMIUM APPOINTMENTS FOR THE MODERN GENTLEMAN",
        "book.button": "BOOK APPOINTMENT",
        "select.services": "SELECT SERVICES",
        "select.time": "CHOOSE A TIME",
        "select.barber": "CHOOSE BARBER",
        "select.date": "SELECT DATE",
        "confirmed": "CONFIRMED",
        "summary": "Summary",
        "total": "Total",
        "next": "Next Step",
        "confirm": "Confirm Booking",
        "back": "Back",
        "nav.home": "HOME",
        "nav.info": "INFO",
        "nav.gallery": "GALLERY",
        "nav.book": "BOOK",
        "nav.manage": "MANAGE BOOKING",
        "manage.title": "Manage Appointments",
        "manage.subtitle": "Enter your phone number to view your appointments.",
        "manage.placeholder": "Phone Number",
        "manage.find": "Find",
        "manage.no_appts": "No appointments found.",
        "manage.cancel": "Cancel",

        "manage.cancel_confirm": "Are you sure you want to cancel this appointment?",
        "manage.cancel_too_late": "Appointments less than 24 hours away cannot be cancelled.",
        "contact.details": "CONTACT",
        "contact.title": "Contact Details",
        "contact.phone": "Phone Number",
        "contact.email": "Email Address",
        "contact.required": "Please provide either phone or email.",
        "contact.disclaimer": "Please enter your email or number to be contacted in case your appointment is not approved.",
        "book.another": "Book Another",
        "contact.name": "Full Name",

        "gallery.interior": "Barber Interior",
        "gallery.tools": "Professional Tools",
        "gallery.lounge": "Waiting Lounge",

        "select.service_prompt": "Select a service to start.",
        "unit.mins": "mins",

        "contact.placeholder_name": "John Doe",
        "contact.placeholder_phone": "+1 234 567 890",
        "contact.placeholder_email": "example@mail.com",

        "admin.login.title": "Admin Access",
        "admin.login.subtitle": "Please enter password",
        "admin.login.button": "Login",
        "admin.login.error": "Wrong Password",
        "admin.nav.dashboard": "Dashboard",
        "admin.nav.termins": "Appointments",
        "admin.nav.services": "Services",
        "admin.nav.barbers": "Barbers",
        "admin.nav.plan": "Plan",
        "admin.nav.availability": "Working Days",
        "admin.logout": "Logout",

        "av.day_off": "Day Off",
        "av.working": "Working",
        "av.cancel": "Cancel",
        "av.set_off": "Mark as Day Off",
        "av.set_working": "Mark as Working",

        "admin.stats.total_revenue": "TOTAL REVENUE",
        "admin.stats.confirmed_appointments": "CONFIRMED APPOINTMENTS",
        "admin.stats.pending_approvals": "PENDING APPROVALS",

        "admin.dashboard.pending_title": "Pending Requests",
        "admin.dashboard.pending_empty": "No pending appointments.",
        "admin.dashboard.pending_subtitle": "New bookings will appear here automatically.",
        "admin.btn.approve": "Approve",
        "admin.btn.reject": "Reject",
        "admin.btn.delete_confirm": "Really reject and delete appointment?",

        "confirmation.cash_warning": "Please remember to bring the total amount in cash.",
        "confirmation.message": "Your appointment is confirmed for {time} on {date}",
        "confirmation.barber": "Barber: {name}",

        "info.location": "Location",
        "info.opening_hours": "Opening Hours",
        "info.get_directions": "Get Directions",
        "info.closed": "Closed",
        "days.monday": "Monday",
        "days.tuesday": "Tuesday",
        "days.wednesday": "Wednesday",
        "days.thursday": "Thursday",
        "days.friday": "Friday",
        "days.saturday": "Saturday",
        "days.sunday": "Sunday",

        "admin.barbers.title": "Team Management",
        "admin.barbers.subtitle": "Manage your barbers",
        "admin.barbers.add_btn": "Add Barber",
        "admin.barbers.delete_confirm": "Are you sure you want to remove this barber?",
        "admin.barbers.modal_title": "Add New Barber",
        "admin.barbers.edit_title": "Edit Barber",
        "admin.barbers.name_label": "Name",
        "admin.barbers.specialty_label": "Specialty",
        "admin.barbers.specialty_placeholder": "e.g. Master Barber",
        "admin.barbers.save": "Save",
        "admin.barbers.cancel": "Cancel",

        "admin.termins.title": "Confirmed Appointments",
        "admin.termins.empty": "No confirmed appointments yet.",
        "admin.termins.empty_sub": "Confirmed bookings will appear here.",
        "admin.termins.date": "Date & Time",
        "admin.termins.customer": "Customer",
        "admin.termins.barber": "Barber",
        "admin.termins.contact": "Contact",
        "admin.termins.services": "Services",
        "admin.termins.total": "Total",
        "admin.termins.delete_confirm": "Permanently delete appointment?",

        "admin.calendar.daily_title": "Daily Schedule",
        "admin.calendar.select_barber": "Select Barber",
        "admin.calendar.select_barber_msg": "Select a team member to manage their working days.",
        "admin.calendar.manage_for": "Manage availability for",
        "admin.months": "January,February,March,April,May,June,July,August,September,October,November,December",
        "admin.days.short": "Mon,Tue,Wed,Thu,Fri,Sat,Sun",
        "admin.services.manage": "Manage Services",
        "admin.services.auto_save": "Changes are saved immediately.",
        "admin.services.new": "New",
        "admin.services.loading": "Loading data...",
        "admin.services.add_new": "New Service",
        "admin.services.confirm_delete": "Are you sure?",
        "admin.services.error_add": "Error adding service",
        "admin.services.add_btn": "Add to List",
        "admin.services.empty": "No services available.",
        "admin.services.name_de": "Name (German) *",
        "admin.services.name_en": "Name (English)",
        "admin.services.name_tr": "Name (Turkish)",
        "admin.services.price": "Price (€) *",
        "admin.services.duration": "Duration (Min)",
        "admin.calendar.no_appts": "No appointments for this day.",
        "admin.calendar.schedule_for": "Schedule for",
        "admin.calendar.view_schedule_msg": "Choose a team member above to view their schedule."
    },
    tr: {
        "hero.title": "RANDEVUNUZ.",
        "hero.subtitle": "MODERN BEYEFENDİLER İÇİN PREMİUM RANDEVULAR",
        "book.button": "RANDEVU AL",
        "select.services": "HİZMETLERİ SEÇİN",
        "select.time": "SAAT SEÇİN",
        "select.barber": "BERBER SEÇİN",
        "select.date": "TARİH SEÇİN",
        "confirmed": "ONAYLANDI",
        "summary": "Özet",
        "total": "Toplam",
        "next": "İleri",
        "confirm": "Onayla",
        "back": "Geri",
        "nav.home": "ANA SAYFA",
        "nav.info": "BİLGİ",
        "nav.gallery": "GALERİ",
        "nav.book": "RANDEVU",
        "nav.manage": "RANDEVU YÖNET",
        "manage.title": "Randevularımı Yönet",
        "manage.subtitle": "Randevularınızı görmek için telefon numaranızı giriniz.",
        "manage.placeholder": "Telefon Numarası",
        "manage.find": "Bul",
        "manage.no_appts": "Randevu bulunamadı.",
        "manage.cancel": "İptal Et",

        "manage.cancel_confirm": "Bu randevuyu iptal etmek istediğinize emin misiniz?",
        "manage.cancel_too_late": "24 saatten az kalan randevular iptal edilemez.",
        "contact.details": "İLETİŞİM",
        "contact.title": "İletişim Bilgileri",
        "contact.phone": "Telefon Numarası",
        "contact.email": "E-Posta",
        "contact.required": "Lütfen telefon veya e-posta giriniz.",
        "contact.disclaimer": "Randevunuzun onaylanmaması durumunda size dönüş yapılabilmesi için lütfen e-posta veya telefon numaranızı giriniz.",
        "book.another": "Başka Randevu Al",
        "contact.name": "Ad Soyad",

        "gallery.interior": "Berber İç Mekan",
        "gallery.tools": "Profesyonel Ekipmanlar",
        "gallery.lounge": "Bekleme Alanı",

        "select.service_prompt": "Başlamak için bir hizmet seçin.",
        "unit.mins": "dk",

        "contact.placeholder_name": "Ahmet Yılmaz",
        "contact.placeholder_phone": "+90 555 123 4567",
        "contact.placeholder_email": "ornek@mail.com",

        "admin.login.title": "Yönetici Girişi",
        "admin.login.subtitle": "Lütfen şifreyi giriniz",
        "admin.login.button": "Giriş Yap",
        "admin.login.error": "Hatalı Şifre",
        "admin.nav.dashboard": "Panel",
        "admin.nav.termins": "Randevular",
        "admin.nav.services": "Hizmetler",
        "admin.nav.barbers": "Berberler",
        "admin.nav.plan": "Planlama",
        "admin.nav.availability": "Çalışma Günleri",
        "admin.logout": "Çıkış Yap",

        "av.day_off": "İzinli",
        "av.working": "Çalışıyor",
        "av.cancel": "Vazgeç",
        "av.set_off": "İzinli Olarak İşaretle",
        "av.set_working": "Çalışıyor Olarak İşaretle",

        "admin.stats.total_revenue": "TOPLAM GELİR",
        "admin.stats.confirmed_appointments": "ONAYLANAN RANDEVULAR",
        "admin.stats.pending_approvals": "ONAY BEKLEYENLER",

        "admin.dashboard.pending_title": "Bekleyen Talepler",
        "admin.dashboard.pending_empty": "Bekleyen randevu yok.",
        "admin.dashboard.pending_subtitle": "Yeni talepler burada otomatik görünür.",
        "admin.btn.approve": "Onayla",
        "admin.btn.reject": "Reddet",
        "admin.btn.delete_confirm": "Randevuyu reddedip silmek istiyor musunuz?",

        "confirmation.cash_warning": "Lütfen yanınızda tutar kadar nakit getirmeyi unutmayın.",
        "confirmation.message": "{date} tarihinde saat {time} için randevunuz onaylandı",
        "confirmation.barber": "Berber: {name}",

        "info.location": "Konum",
        "info.opening_hours": "Çalışma Saatleri",
        "info.get_directions": "Yol Tarifi Al",
        "info.closed": "Kapalı",
        "days.monday": "Pazartesi",
        "days.tuesday": "Salı",
        "days.wednesday": "Çarşamba",
        "days.thursday": "Perşembe",
        "days.friday": "Cuma",
        "days.saturday": "Cumartesi",
        "days.sunday": "Pazar",

        "admin.barbers.title": "Takım Yönetimi",
        "admin.barbers.subtitle": "Berberlerinizi yönetin",
        "admin.barbers.add_btn": "Berber Ekle",
        "admin.barbers.delete_confirm": "Bu berberi silmek istediğinize emin misiniz?",
        "admin.barbers.modal_title": "Yeni Berber Ekle",
        "admin.barbers.edit_title": "Berberi Düzenle",
        "admin.barbers.name_label": "Ad Soyad",
        "admin.barbers.specialty_label": "Uzmanlık",
        "admin.barbers.specialty_placeholder": "Örn. Usta Berber",
        "admin.barbers.save": "Kaydet",
        "admin.barbers.cancel": "İptal",

        "admin.termins.title": "Onaylanan Randevular",
        "admin.termins.empty": "Henüz onaylanmış randevu yok.",
        "admin.termins.empty_sub": "Onaylananlar burada görünür.",
        "admin.termins.date": "Tarih & Saat",
        "admin.termins.customer": "Müşteri",
        "admin.termins.barber": "Berber",
        "admin.termins.contact": "İletişim",
        "admin.termins.services": "Hizmetler",
        "admin.termins.total": "Toplam",
        "admin.termins.delete_confirm": "Randevuyu kalıcı olarak sil?",

        "admin.calendar.daily_title": "Günlük Program",
        "admin.calendar.select_barber": "Berber Seç",
        "admin.calendar.select_barber_msg": "Çalışma günlerini yönetmek için birini seçin.",
        "admin.calendar.manage_for": "Yönetilen kişi:",
        "admin.months": "Ocak,Şubat,Mart,Nisan,Mayıs,Haziran,Temmuz,Ağustos,Eylül,Ekim,Kasım,Aralık",
        "admin.days.short": "Pzt,Sal,Çar,Per,Cum,Cmt,Paz",
        "admin.services.manage": "Hizmetleri Yönet",
        "admin.services.auto_save": "Değişiklikler anında kaydedilir.",
        "admin.services.new": "Yeni",
        "admin.services.loading": "Veriler yükleniyor...",
        "admin.services.add_new": "Yeni Hizmet",
        "admin.services.confirm_delete": "Emin misiniz?",
        "admin.services.error_add": "Ekleme hatası",
        "admin.services.add_btn": "Listeye Ekle",
        "admin.services.empty": "Mevcut hizmet yok.",
        "admin.services.name_de": "İsim (Almanca) *",
        "admin.services.name_en": "İsim (İngilizce)",
        "admin.services.name_tr": "İsim (Türkçe)",
        "admin.services.price": "Fiyat (€) *",
        "admin.services.duration": "Süre (Dk)",
        "admin.calendar.no_appts": "Bugün için randevu yok.",
        "admin.calendar.schedule_for": "Planı:",
        "admin.calendar.view_schedule_msg": "Planını görmek için bir ekip üyesi seçin."
    },
    ku: {
        "hero.title": "RANDEVÛYA TE.",
        "hero.subtitle": "RANDEVÛYÊN BI KALÎTE BO CAMÊRÊN MODERN",
        "book.button": "RANDEVÛ BIGIRE",
        "select.services": "XIZMETAN HILBIJÊRE",
        "select.time": "DEM HILBIJÊRE",
        "select.barber": "BERBER HILBIJÊRE",
        "select.date": "TARÎX HILBIJÊRE",
        "confirmed": "HAT ERÊKIRIN",
        "summary": "Kurte",
        "total": "Giştî",
        "next": "Pêşve",
        "confirm": "Erê Bike",
        "back": "Paşve",
        "nav.home": "DESTPÊK",
        "nav.info": "AGAHÎ",
        "nav.gallery": "GALERÎ",
        "nav.book": "RANDEVÛ",
        "nav.manage": "RANDEVÛ BIRÊVE BIBE",
        "manage.title": "Randevûyan Birêve Bibe",
        "manage.subtitle": "Ji bo dîtina randevûyan hejmara xwe binivîse.",
        "manage.placeholder": "Hejmara Telefonê",
        "manage.find": "Bibîne",
        "manage.no_appts": "Randevû nehat dîtin.",
        "manage.cancel": "Betal Bike",

        "manage.cancel_confirm": "Tu dixwazî vê randevûyê betal bikî?",
        "manage.cancel_too_late": "Randevûyên ku ji 24 saetan kêmtir dem mane nayên betalkirin.",
        "contact.details": "TÊKILÎ",
        "contact.title": "Agahiyên Têkiliyê",
        "contact.phone": "Hejmara Telefonê",
        "contact.email": "E-Posta",
        "contact.required": "Zehmet nebe telefon an e-posta binivîse.",
        "contact.disclaimer": "Heke randevûya te neyê erêkirin, ji bo em karibin li te vegerin ji kerema xwe e-posta an hejmara xwe binivîse.",
        "book.another": "Randevûyek Din Bigire",
        "contact.name": "Nav û Paşnav",

        "gallery.interior": "Navxweya Berber",
        "gallery.tools": "Amûrên Profesyonel",
        "gallery.lounge": "Cihê Bendewarîyê",

        "select.service_prompt": "Ji bo destpêkirinê xizmetek hilbijêre.",
        "unit.mins": "xûlek",

        "contact.placeholder_name": "Azad Şêrgo",
        "contact.placeholder_phone": "+49 ...",
        "contact.placeholder_email": "mînak@mail.com",

        "admin.login.title": "Têketina Rêveber",
        "admin.login.subtitle": "Zehmet nebe şîfreyê binivîse",
        "admin.login.button": "Têkeve",
        "admin.login.error": "Şîfre Çewt e",
        "admin.nav.dashboard": "Panel",
        "admin.nav.termins": "Randevû",
        "admin.nav.services": "Xizmet",
        "admin.nav.barbers": "Berber",
        "admin.nav.plan": "Plan",
        "admin.nav.availability": "Rojên Xebatê",
        "admin.logout": "Derkeve",

        "av.day_off": "bêhnvedan",
        "av.working": "Dixebite",
        "av.cancel": "Dev jê berde",
        "av.set_off": "Weke Bêhnvedan Nîşan Bide",
        "av.set_working": "Weke Dixebite Nîşan Bide",

        "admin.stats.total_revenue": "DAHATIN",
        "admin.stats.confirmed_appointments": "RANDEVÛYÊN ERÊKIRÎ",
        "admin.stats.pending_approvals": "YÊN LI BENDA ERÊKIRINÊ",

        "admin.dashboard.pending_title": "Daxwazên Li Bendê",
        "admin.dashboard.pending_empty": "Randevûyên li bendê tune ne.",
        "admin.dashboard.pending_subtitle": "Daxwazên nû dê li vir xuya bibin.",
        "admin.btn.approve": "Erê Bike",
        "admin.btn.reject": "Red Bike",
        "admin.btn.delete_confirm": "Tu dixwazî randevûyê red bikî û jê bibî?",

        "confirmation.cash_warning": "Ji kerema xwe ji bîr neke ku hûn drav bi xwe re bînin.",
        "confirmation.message": "Randevûya we ji bo {date} saet {time} hat erêkirin",
        "confirmation.barber": "Berber: {name}",

        "info.location": "Cih",
        "info.opening_hours": "Demjimêrên Xebatê",
        "info.get_directions": "Rê Tarîf Bike",
        "info.closed": "Girtî",
        "days.monday": "Duşem",
        "days.tuesday": "Sêşem",
        "days.wednesday": "Çarşem",
        "days.thursday": "Pêncşem",
        "days.friday": "În",
        "days.saturday": "Şemî",
        "days.sunday": "Yekşem",

        "admin.barbers.title": "Rêveberiya Tîmê",
        "admin.barbers.subtitle": "Berberên xwe birêve bibin",
        "admin.barbers.add_btn": "Berber Zêde Bike",
        "admin.barbers.delete_confirm": "Tu dixwazî vê berberê jê bibî?",
        "admin.barbers.modal_title": "Berberekî Nû Zêde Bike",
        "admin.barbers.edit_title": "Berber Sererast Bike",
        "admin.barbers.name_label": "Nav û Paşnav",
        "admin.barbers.specialty_label": "Pisporî",
        "admin.barbers.specialty_placeholder": "mînak. Hostayê Berber",
        "admin.barbers.save": "Tomar Bike",
        "admin.barbers.cancel": "Betal Bike",

        "admin.termins.title": "Randevûyên Erêkirî",
        "admin.termins.empty": "Hêj randevûyên erêkirî tune ne.",
        "admin.termins.empty_sub": "Randevûyên erêkirî dê li vir xuya bibin.",
        "admin.termins.date": "Dîrok & Dem",
        "admin.termins.customer": "Mişterî",
        "admin.termins.barber": "Berber",
        "admin.termins.contact": "Têkilî",
        "admin.termins.services": "Xizmet",
        "admin.termins.total": "Giştî",
        "admin.termins.delete_confirm": "Randevû bi temamî jê bibe?",

        "admin.calendar.daily_title": "Bernameya Rojane",
        "admin.calendar.select_barber": "Berber Hilbijêre",
        "admin.calendar.select_barber_msg": "Ji bo rêvebirina rojên xebatê endamek hilbijêre.",
        "admin.calendar.manage_for": "Rêveberiya berdestbûnê ji bo",
        "admin.months": "Rêbendan,Reşemî,Adar,Avrêl,Gulan,Pûşper,Tîrmeh,Gelawêj,Rezber,Cotmeh,Mijdar,Berfanbar",
        "admin.days.short": "Duş,Sêş,Çar,Pên,În,Şem,Yek",
        "admin.services.manage": "Rêveberiya Xizmetan",
        "admin.services.auto_save": "Guhertin tavilê tên tomarkirin.",
        "admin.services.new": "Nû",
        "admin.services.loading": "Dane tên barkirin...",
        "admin.services.add_new": "Xizmetek Nû",
        "admin.services.confirm_delete": "Tu piştrast î?",
        "admin.services.error_add": "Çewtî di lêzêdekirinê de",
        "admin.services.add_btn": "Li Listeyê Zêde Bike",
        "admin.services.empty": "Xizmet tune ne.",
        "admin.services.name_de": "Nav (Almanî) *",
        "admin.services.name_en": "Nav (Îngilîzî)",
        "admin.services.name_tr": "Nav (Tirkî)",
        "admin.services.price": "Biha (€) *",
        "admin.services.duration": "Dem (Xûlek)",
        "admin.calendar.no_appts": "Ji bo vê rojê randevu tune.",
        "admin.calendar.schedule_for": "Plana ji bo",
        "admin.calendar.view_schedule_msg": "Ji bo dîtina planê endamekî tîmê hilbijêre."
    },
    ar: {
        "hero.title": "موعدك.",
        "hero.subtitle": "مواعيد متميزة للرجل العصري",
        "book.button": "حجز موعد",
        "select.services": "اختر الخدمات",
        "select.time": "اختر الوقت",
        "select.barber": "اختر الحلاق",
        "select.date": "اختر التاريخ",
        "confirmed": "تم التأكيد",
        "summary": "ملخص",
        "total": "الإجمالي",
        "next": "التالي",
        "confirm": "تأكيد",
        "back": "عودة",
        "nav.home": "الرئيسية",
        "nav.info": "معلومات",
        "nav.gallery": "المعرض",
        "nav.book": "حجز",
        "nav.manage": "إدارة الحجز",
        "manage.title": "إدارة المواعيد",
        "manage.subtitle": "أدخل رقم هاتفك لعرض مواعيدك.",
        "manage.placeholder": "رقم الهاتف",
        "manage.find": "بحث",
        "manage.no_appts": "لم يتم العثور على مواعيد.",
        "manage.cancel": "إلغاء",
        "manage.cancel_confirm": "هل أنت متأكد أنك تريد إلغاء هذا الموعد؟",
        "manage.cancel_too_late": "لا يمكن إلغاء المواعيد التي تقل عن 24 ساعة.",
        "contact.details": "اتصال",
        "contact.title": "تفاصيل الاتصال",
        "contact.phone": "رقم الهاتف",
        "contact.email": "البريد الإلكتروني",
        "contact.required": "يرجى تقديم الهاتف أو البريد الإلكتروني.",
        "contact.disclaimer": "يرجى إدخال بريدك الإلكتروني أو رقم هاتفك ليتم الاتصال بك في حال عدم الموافقة على موعدك.",
        "book.another": "حجز موعد آخر",
        "contact.name": "الاسم الكامل",

        "gallery.interior": "تصميم الصالون",
        "gallery.tools": "أدوات احترافية",
        "gallery.lounge": "صالة الانتظار",

        "select.service_prompt": "اختر خدمة للبدء.",
        "unit.mins": "دقيقة",

        "contact.placeholder_name": "الاسم",
        "contact.placeholder_phone": "+90 ...",
        "contact.placeholder_email": "example@mail.com",

        "admin.login.title": "دخول المسؤول",
        "admin.login.subtitle": "يرجى إدخال كلمة المرور",
        "admin.login.button": "دخول",
        "admin.login.error": "كلمة المرور غير صحيحة",
        "admin.nav.dashboard": "لوحة التحكم",
        "admin.nav.termins": "المواعيد",
        "admin.nav.services": "الخدمات",
        "admin.nav.barbers": "الحلاقين",
        "admin.nav.plan": "خطة العمل",
        "admin.nav.availability": "أيام العمل",
        "admin.logout": "تسجيل خروج",

        "av.day_off": "عطلة",
        "av.working": "عمل",
        "av.cancel": "إلغاء",
        "av.set_off": "تحديد كعطلة",
        "av.set_working": "تحديد كعمل",

        "admin.stats.total_revenue": "إجمالي الإيرادات",
        "admin.stats.confirmed_appointments": "مواعيد مؤكدة",
        "admin.stats.pending_approvals": "طلبات قيد الانتظار",

        "admin.dashboard.pending_title": "طلبات معلقة",
        "admin.dashboard.pending_empty": "لا توجد مواعيد معلقة.",
        "admin.dashboard.pending_subtitle": "ستظهر الحجوزات الجديدة هنا تلقائيًا.",
        "admin.btn.approve": "موافقة",
        "admin.btn.reject": "رفض",
        "admin.btn.delete_confirm": "هل تريد حقًا رفض وحذف الموعد؟",

        "confirmation.cash_warning": "يرجى تذكر إحضار المبلغ نقدًا.",
        "confirmation.message": "تم تأكيد موعدك في {time} بتاريخ {date}",
        "confirmation.barber": "الحلاق: {name}",

        "info.location": "الموقع",
        "info.opening_hours": "ساعات العمل",
        "info.get_directions": "الحصول على الاتجاهات",
        "info.closed": "مغلق",
        "days.monday": "الاثنين",
        "days.tuesday": "الثلاثاء",
        "days.wednesday": "الأربعاء",
        "days.thursday": "الخميس",
        "days.friday": "الجمعة",
        "days.saturday": "السبت",
        "days.sunday": "الأحد",

        "admin.barbers.title": "إدارة الفريق",
        "admin.barbers.subtitle": "إدارة الحلاقين",
        "admin.barbers.add_btn": "إضافة حلاق",
        "admin.barbers.delete_confirm": "هل أنت متأكد أنك تريد حذف هذا الحلاق؟",
        "admin.barbers.modal_title": "إضافة حلاق جديد",
        "admin.barbers.edit_title": "تعديل حلاق",
        "admin.barbers.name_label": "الاسم",
        "admin.barbers.specialty_label": "التخصص",
        "admin.barbers.specialty_placeholder": "مثال: حلاق محترف",
        "admin.barbers.save": "حفظ",
        "admin.barbers.cancel": "إلغاء",

        "admin.termins.title": "مواعيد مؤكدة",
        "admin.termins.empty": "لا توجد مواعيد مؤكدة بعد.",
        "admin.termins.empty_sub": "ستظهر الحجوزات المؤكدة هنا.",
        "admin.termins.date": "التاريخ والوقت",
        "admin.termins.customer": "العميل",
        "admin.termins.barber": "الحلاق",
        "admin.termins.contact": "اتصال",
        "admin.termins.services": "الخدمات",
        "admin.termins.total": "الإجمالي",
        "admin.termins.delete_confirm": "حذف الموعد نهائيًا؟",

        "admin.calendar.daily_title": "الجدول اليومي",
        "admin.calendar.select_barber": "اختر حلاق",
        "admin.calendar.select_barber_msg": "اختر عضوًا في الفريق لإدارة أيام عمله.",
        "admin.calendar.manage_for": "إدارة التوافر لـ",
        "admin.months": "يناير,فبراير,مارس,أبريل,مايو,يونيو,يوليو,أغسطس,سبتمبر,أكتوبر,نوفمبر,ديسمبر",
        "admin.days.short": "ن,ث,ر,خ,ج,س,ح",
        "admin.services.manage": "إدارة الخدمات",
        "admin.services.auto_save": "يتم حفظ التغييرات تلقائيًا.",
        "admin.services.new": "جديد",
        "admin.services.loading": "جارٍ تحميل البيانات...",
        "admin.services.add_new": "خدمة جديدة",
        "admin.services.confirm_delete": "هل أنت متأكد؟",
        "admin.services.error_add": "خطأ في الإضافة",
        "admin.services.add_btn": "يضيف للقائمة",
        "admin.services.empty": "لا توجد خدمات متاحة.",
        "admin.services.name_de": "الاسم (الألمانية) *",
        "admin.services.name_en": "الاسم (الإنجليزية)",
        "admin.services.name_tr": "الاسم (التركية)",
        "admin.services.price": "السعر (€) *",
        "admin.services.duration": "المدة (دقيقة)",
        "admin.calendar.no_appts": "لا توجد مواعيد لهذا اليوم.",
        "admin.calendar.schedule_for": "جدول لـ",
        "admin.calendar.view_schedule_msg": "اختر عضوًا في الفريق لعرض جدوله."
    }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    // Start with null to allow client-side hydration match (but t() will handle fallback)
    const [language, setLanguageState] = useState<Language>(null);

    // Load from localStorage on mount
    useEffect(() => {
        const saved = localStorage.getItem('berber_language') as LanguageCode;
        if (saved && ['de', 'en', 'tr', 'ku', 'ar'].includes(saved)) {
            setLanguageState(saved);
        }
    }, []);

    // Handle RTL
    useEffect(() => {
        if (language === 'ar') {
            document.documentElement.dir = 'rtl';
            document.documentElement.lang = 'ar';
        } else {
            document.documentElement.dir = 'ltr';
            document.documentElement.lang = language || 'de';
        }
    }, [language]);

    const setLanguage = (lang: Language) => {
        if (lang) {
            localStorage.setItem('berber_language', lang);
        } else {
            localStorage.removeItem('berber_language');
        }
        setLanguageState(lang);
    };

    const t = (key: string) => {
        // Fallback to 'de' if language is not yet loaded (e.g. generic SSR or pre-mount)
        // This prevents showing keys like 'admin.login.title' during hydration
        const currentLang = language || 'de';
        return TRANSLATIONS[currentLang as LanguageCode][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
